# Generated by Django 4.2.2 on 2024-03-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_delete_materiacrear_materia_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='correo',
            new_name='email',
        ),
    ]
